mail.host=smtp.gmail.com
mail.port=587
mail.username=damsara.chethiyaa@gmail.com
mail.password=xuqorwsfapfnevje
app.mail=damsara.chethiyaa@gmail.com
app.name=NeonGear
app.url=http://localhost:8080/neongear
app.public.url=http://localhost:8080/neongear