package lk.jiat.smarttrade.dto;

public class PayHereDTO {
    /* make dto for the required PayHere parameters
    Required Parameters
    merchant_id - PayHere Merchant ID
    return_url - URL to redirect users when success
    cancel_url - URL to redirect users when cancelled
    notify_url - URL to call back the status of the payment (Needs to be a URL accessible on a public IP/domain)
    first_name - Customer’s First Name
    last_name - Customer’s Last Name
    email - Customer’s Email
    phone - Customer’s Phone No
    address - Customer’s Address Line1 + Line2
    city - Customer’s City
    country - Customer’s Country
    order_id - Order ID generated by the merchant
    items - Item title or Order/Invoice number
    currency - Currency Code (LKR/USD)
    amount - Total Payment Amount
    hash - Generated hash value as mentioned below (*Required from 2023-01-16)
     */
    private boolean sandbox;
    private String merchant_id;
    private String return_url;
    private String cancel_url;
    private String notify_url;
    private String first_name;
    private String last_name;
    private String email;
    private String phone;
    private String address;
    private String city;
    private String country;
    private String order_id;
    private String items;
    private String currency;
    private String amount;
    private String hash;

    public boolean isSandbox() {
        return sandbox;
    }

    public void setSandbox(boolean sandbox) {
        this.sandbox = sandbox;
    }

    public String getMerchantId() {
        return merchant_id;
    }

    public void setMerchantId(String merchant_id) {
        this.merchant_id = merchant_id;
    }

    public String getReturnURL() {
        return return_url;
    }

    public void setReturnURL(String return_url) {
        this.return_url = return_url;
    }

    public String getCancelURL() {
        return cancel_url;
    }

    public void setCancelURL(String cancel_url) {
        this.cancel_url = cancel_url;
    }

    public String getNotifyURL() {
        return notify_url;
    }

    public void setNotifyURL(String notify_url) {
        this.notify_url = notify_url;
    }

    public String getFirstName() {
        return first_name;
    }

    public void setFirstName(String first_name) {
        this.first_name = first_name;
    }

    public String getLastName() {
        return last_name;
    }

    public void setLastName(String last_name) {
        this.last_name = last_name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getOrderId() {
        return order_id;
    }

    public void setOrderId(String orderId) {
        this.order_id = orderId;
    }

    public String getItems() {
        return items;
    }

    public void setItems(String items) {
        this.items = items;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }
}
